### ISSUE TITLE
The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting

### ISSUE THREAD

**Issue by cnbillow** [zaxlct/MxOnline_Django#1]
STATICFILES_DIRS 和 STATIC_ROOT的设置为同一目录报错。
修改了STATIC_ROOT目录，可以运行，但是找不到\MxOnline_Django\templates目录下的模板文件。
请问怎样解决？

**Comment by kele59** [comment]
@cnbillow 
`STATIC_ROOT = os.path.join(BASE_DIR, 'static')`
这行代码开发的时候不用加，可以注释掉。
这个是项目上线部署时设置的。
