### ISSUE TITLE
困惑

### ISSUE THREAD

**Issue by Bajie0624** [zaxlct/MxOnline_Django#11]
您好，我出现过ImportError: No module named courses，这个问题，想问下您出现过么？根本找不到解决办法，代码是和您的一样，我也是按照视频里面那样写的。

**Comment by kele59** [comment]
你的 `settings.py` 里是否有如下的配置：
``` python
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

INSTALLED_APPS = [
    'courses'
]
```

如果这样还不能解决你的问题，可以发一下你的代码截图。
