### ISSUE TITLE
为什么我部署后登录网站后台，没有数据啊？而且添加数据之后，前端也没有呈现？

### ISSUE THREAD

**Issue by hunantangke** [zaxlct/MxOnline_Django#14]

**Comment by kele59** [comment]
部署网站后，你需要网数据库里添加数据才有数据呀。
域名需要先备案，然后绑定到服务器，相关的教程网上很多，可以百度一下哈。
你可能需要一点 mysql 的知识，来看一下为什么添加数据后前台没显示，或者你本地先跑一下代码试试，正常了再部署看看。
