### ISSUE TITLE
注册部分的邮件发送功能，报这个编码错误，你是怎么解决的啊

### ISSUE THREAD

**Issue by coderxiaoyang** [zaxlct/MxOnline_Django#16]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-8: ordinal not in range(128)

**Comment by kele59** [comment]
python 2.7 ？
文件头部是否添加了 
`# -*- coding: utf-8 -*-`

**Comment by coderxiaoyang** [comment]
python3

**Comment by kele59** [comment]
@lufeisan 
参考一下这个？
http://blog.csdn.net/olanlanxiari/article/details/48201231
