### ISSUE TITLE
用户无法退出

### ISSUE THREAD

**Issue by SayHITell** [zaxlct/MxOnline_Django#17]
首页的用户登录之后点击退出，页面刷新但是用户并未退出。我认为是跟后台登录了有关，一开始是可以退出的，但是我后台登录了之后就不行了。

**Comment by kele59** [comment]
用户退出的相关代码是不是有点问题？ 比对一下我的源码，看看是不是哪里马虎写错了，试试，亲

还有，可以 DEBUG 下，看看点击退出后，代码在哪里出了问题，退出的时候是否进入到了退出的逻辑

**Comment by SayHITell** [comment]
好像是这样的：如果用的是设置的超级用户登录的话，就无法退出，调试结果就是不会进入LogoutView而是直接进入IndexView；如果只是用普通用户登录的话就能正常运行。

**Comment by kele59** [comment]
@SayHITell 超级用户你登录，admin ，然后点击 admin 里的右上角退出

**Comment by SayHITell** [comment]
我在Chrome下试了很多次，把cookie和缓存清空可以登录退出，然后再一次登录就退出不了了。

**Comment by kele59** [comment]
@SayHITell 清除 cookie 肯定能退出，因为 cookie 里保存着登录需要的 token ，这不是解决问题的办法。

**Comment by SayHITell** [comment]
嗯，所以我也不知道这是哪出错了，代码是直接用你的没改过
