### ISSUE TITLE
manage.py 运行不了

### ISSUE THREAD

**Issue by MisterDeng** [zaxlct/MxOnline_Django#19]
manage.py 运行createsuperuser失败   我发现os.environ.setdefault("DJANGO_SETTINGS_MODULE", "imooc.settingsdev") 依然不行

**Comment by MisterDeng** [comment]
python manage.py createsuperuser
这个命令是可以的  用pycharm的tool就不行

**Comment by kele59** [comment]
是否按照 README  里写的那样更改了 pycharm 的环境变量？

**Comment by MisterDeng** [comment]
<img width="476" alt="qq20170522-140741 2x" src="https://cloud.githubusercontent.com/assets/12538286/26294675/133b00c8-3ef8-11e7-91ad-0d3a5ecf8f6a.png">

**Comment by MisterDeng** [comment]
还有为什么感觉后台管理这么慢呢，特别是课程那一块，明明是在本地部署的，前台还好

**Comment by kele59** [comment]
现在 manage.py 能运行了吧？
后台管理慢，这个我也不清楚 = =，
