### ISSUE TITLE
按现在的目录结构，import 错误

### ISSUE THREAD

**Issue by cnbillow** [zaxlct/MxOnline_Django#2]
\MxOnline_Django\imooc\urls.py
`import xadmin

# from users.views import user_login
from users.views import IndexView
from users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView, ResetView, ModifyPwdView, LogoutView`
按当前的目录结构这些都import不到吧。应该怎样设置呢？

**Comment by kele59** [comment]
设置一下 app 目录，在 `setting.py` 里有对应的代码：
```
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
```
设置完之后，原本需要这么写的代码：
`from app.users.views import IndexView`
只需要这么写：
`from users.views import IndexView`
前面不需要加 `apps` 了


但是如果你用的是 pycharm ，它可能会报错，你需要右键 apps 这个目录，mark 成 Sources Root

**Comment by cnbillow** [comment]
3q
