### ISSUE TITLE
之前登录过的话，无法退出，点击退出登录，页面刷新之后仍旧读取登录信息自动登录

### ISSUE THREAD

**Issue by VanRitzOwen** [zaxlct/MxOnline_Django#20]

**Comment by kele59** [comment]
能贴一下退出部分的代码吗？还是说是克隆了我的代码出现的问题？

**Comment by VanRitzOwen** [comment]
回复及时，点个赞！克隆的你的代码，点退出登录之后，logout（request）不起作用。

**Comment by kele59** [comment]
mater 分支？
代码报错了吗？

**Comment by VanRitzOwen** [comment]
嗯嗯，是的

**Comment by VanRitzOwen** [comment]
我手动在chrome开发人员工具里删除了sessionid，刷新页面就成未登录状态了，清除session的代码也没有管用。。

**Comment by kele59** [comment]
登录的用户是不是超级用户？
新注册一个用户，登录一下，再点击登出是否也出现这种情况？

**Comment by VanRitzOwen** [comment]
所有用户都是无法退出，sessionid后台是一直存在的，目前没找到办法清空sessionid

**Comment by kele59** [comment]
手动清空 sessionid 不是个好办法，我克隆代码调试下。之前的代码不小心删了， = =哈哈

**Comment by kele59** [comment]
@VanRitzOwen 我刚刚这么执行了一下，没发现问题
```bash
# 建立虚拟环境
git clone https://github.com/zaxlct/MxOnline_Django
make dev
# 建立一个名为 imooc 数据库
make migrate
make run
# 注册账号
# 登录账号
# 点击登出，刷新页面，已登出
```

**Comment by VanRitzOwen** [comment]
啊？为什么你的环境可以正常退出啊。。

**Comment by kele59** [comment]
@VanRitzOwen 再另外克隆下项目，重新启动试试？

**Comment by VanRitzOwen** [comment]
大神，Master分支为什么需要开代理才能加载jQuery？不开代理console显示加载Timeout。

**Comment by kele59** [comment]
@VanRitzOwen 什么意思？什么代理？

**Comment by Lefttyre** [comment]
我也遇到了这个问题，我加断点后发现LogoutView.get 其实没有被调到。费解，master分支

**Comment by kele59** [comment]
@Lefttyre 为毛我本地测试没问题 2333....

**Comment by Lefttyre** [comment]
@zaxlct, 哈哈，我也很是费解，再次测试了一下chrome 和Firefox 都有这个问题，断点断不到，但是360没有问题。本人菜鸟，也debug不出其中的缘由了，前面两个浏览器手动删除缓存内容后，又可以执行到logout一次。
