### ISSUE TITLE
大神进入xadmin没有样式

### ISSUE THREAD

**Issue by 95hx** [zaxlct/MxOnline_Django#21]
http://127.0.0.1:8000/admin/能打开    没样式

**Comment by 95hx** [comment]
可以了好像改了下debug为false就ok

**Comment by kele59** [comment]
@95hx 
 DEBUG=False 时 Django 不会用自带的 server 去加载 js/css/img 等静态文件，需要用 nginx 之类的去做静态文件的 server。
