### ISSUE TITLE
数据库编码问题

### ISSUE THREAD

**Issue by wsyhhhh** [zaxlct/MxOnline_Django#22]
我通过docker部署插入数据就可以显示中文，自己手动部署中文就显示的是？？，然后我在数据库里设置了编码utf8。通过数据库命令查看编码格式也是utf8了，为什么中文还是显示的问号

**Comment by kele59** [comment]
@wsyhhhh 
额，不好意思，数据库方面我不太熟....

**Comment by wsyhhhh** [comment]
额额，那你当时数据库的编码是怎么配置的？

**Comment by kele59** [comment]
@wsyhhhh 就按照前几章视频里那么配置的。。。没特殊的配置啥的
