### ISSUE TITLE
把Django项目部署到Nginx+Uwsgi上出现问题

### ISSUE THREAD

**Issue by Dee-Wang** [zaxlct/MxOnline_Django#23]
先膜拜大神，我也在跟着教程做这个项目，只是视频不全，最后上线这一部分的视频没有。
       我项目使用Django自带的服务器运行没问题，想把这个项目部署到Nginx和Uwsgi上面，按照网上相关的博客介绍，也参考了您的博文：http://blog.csdn.net/HeatDeath/article/details/70510847，但是走完所有步骤以后不知道该怎么启动项目了，现在uwsgi 状态没有报错，nginx也正常的启动了，但是不知道要怎么去像`python manage.py runserver`一样启动项目，我不知道是我的代码出了问题，还是落下了步骤，或者其他的原因。
       大神可否写一篇博文，或者在github下面介绍下怎样将项目正确的部署到Nginx+Uwsgi上面，并且重新启动，或者再这里指点我一下接下来要做什么，才能像原来的那样运行整个项目。
       跪谢大神！

**Comment by kele59** [comment]
@Dee-Wang 我写博客了呀，
[Linux/Mac/Windos 用 Docker 部署项目步骤](https://github.com/zaxlct/MxOnline_Django/blob/master/Deployment.md)
