### ISSUE TITLE
请问这个比起php来说会不会要多一些机器

### ISSUE THREAD

**Issue by nullscc** [zaxlct/MxOnline_Django#24]
对这个项目非常感兴趣，就是担心会不会比起php会不会要更多的机器。额外话题，像这样视频分享网站，性能损耗主要在哪里呢？

**Comment by kele59** [comment]
@nullscc 我只是纯技术方面对这个项目感兴趣，至于部署，用什么语音来实现，性能损耗等等还不太了解

**Comment by nullscc** [comment]
@zaxlct 奥，能用python做我就不想用php做，不知道视频分享网站适不适合用python做，毕竟执行速度~

**Comment by kele59** [comment]
@nullscc 速度的话，语言本身的影响微乎及微。哪怕你用 C 写的视频分享网站，视频资源本身没有做加速，还是会很慢。

**Comment by nullscc** [comment]
@zaxlct 你的意思用python做这种视频分享网站，和php比起来不会有很明显的机器负担咯~

**Comment by kele59** [comment]
@nullscc 我的意思是不要去太纠结选择哪个语言，python，node，php 都行。重点应该放到视频资源上，比如最简单的方式就是，开通一些七牛、又拍云等第三方服务商的视频加速服务等。

**Comment by nullscc** [comment]
好的，多谢解答，有空研究下，想用python做个商业视频分享网站。
