### ISSUE TITLE
后台管理登录.

### ISSUE THREAD

**Issue by kangqiao** [zaxlct/MxOnline_Django#25]
你好, 我最近也在做类似这个架构的公益项目: https://github.com/kangqiao/lqtripitaka
非常希望您也能够加入龙泉寺大藏经平台.

运行你的项目. 你更改了AUTH_USER_MODEL
怎么创建一个超级管理员账号了?
想登录后台. 看看.
另外能给出一些测试数据到项目中么?
方便 初始化时导入数据库中. 
非常感谢!!!

**Comment by kele59** [comment]
@kangqiao 
这是一个开源项目，供 django 入门。

如何创建一个超级管理员账号，可以百度一下，应该能得到很多答案。

创建成功后，登录后台，可以动手的在后台添加一些数据，然后前端页面就自动有数据了。

测试数据我这边也没有...之前格式化了电脑....
