### ISSUE TITLE
问下关于list_filter的问题

### ISSUE THREAD

**Issue by JackZhang1024** [zaxlct/MxOnline_Django#27]
我设置 list_filter = ['code', 'email', 'send_type', 'send_time'] 为什么在过滤器那块看不下拉框
Django==1.9.8 Python 2.7

**Comment by kele59** [comment]
@zhangfengzhou 贴一下 adminx.py 详细的代码看看？

**Comment by kele59** [comment]
![image](https://user-images.githubusercontent.com/14342431/27637274-bcde2ab8-5c41-11e7-81dd-b50f1b43102e.png)
是不是按照这种格式写的呢

**Comment by JackZhang1024** [comment]
我在models中加了如下代码
import sys
reload(sys)
sys.setdefaultencoding("utf-8")
问题解决了 但是不知道为什么

**Comment by kele59** [comment]
@zhangfengzhou 你用的 python 2.x 版本？
你可以在文件顶部添加 `# -*- coding: utf-8 -*-` 试试
