### ISSUE TITLE
关于用户和用户组

### ISSUE THREAD

**Issue by wsyhhhh** [zaxlct/MxOnline_Django#28]
你好，我把想让一部分用户也有发布课程的权限，所以创建了一个用户组，我该如何在admin后台管理界面
面把用户加入到这个用户组里。

**Comment by kele59** [comment]
@wsyhhhh 
用超级管理员账号登录 admin 后台，找到发布课程那块，应该能看到给用户分配权限的地方

**Comment by wsyhhhh** [comment]
发布课程里面没有啊，只有增加课程，章节，课程资源什么的

**Comment by kele59** [comment]
@wsyhhhh 不对呀，应该有设置权限的地方，你再仔细找找？或者百度一下，关于权限这一块我了解不是很深。。

**Comment by wsyhhhh** [comment]
我在django里自带的admin里找到了。。在xadmin里没找到，在xadmin官网的测试案例里也没有
找到

**Comment by kele59** [comment]
@wsyhhhh 额，好吧。。这个可能是 xadmin 的问题吧
