### ISSUE TITLE
找不到头部导航路径

### ISSUE THREAD

**Issue by cnbillow** [zaxlct/MxOnline_Django#3]
头部导航中，直接写的模板路径。在pycharm中运行，找不到这些路径。该怎样设置呢？
\MxOnline_Django\templates\base.html
`              <li>
                <a href="teachers-list.html">授课教师</a>
              </li>
              <li class="active"><a href="org-list.html">授课机构</a></li>
`

**Comment by kele59** [comment]
```html
<a href="teachers-list.html">授课教师</a>
```
在 Django 的模板里理论上这么写是不对的，我偷懒了。
在 `imooc/urls.py` 里有这么一句代码：
```python
 #课程机构相关 URL
url(r'^org/', include('organization.urls', namespace='org')),
```
在 `apps/organization/urls.py` 里有这么一行：
```python
url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),
```

所以在正确应该这么写：
```html
<a href="{%  url 'org: teacher_list' %}">授课教师</a>
```
如果你了解 django url 方面的知识，很容易理解。

明天我会把项目里 template 目录下的所有 html ，排查一下，改一下 url
