### ISSUE TITLE
'NoneType' object has no attribute 'has_header'

### ISSUE THREAD

**Issue by ghost** [zaxlct/MxOnline_Django#35]
在后台新增课程出现问题。

环境配置:
python 27
Django 1.10.5
xadmin 0.6

**Comment by kele59** [comment]
@a8926764 
代码截图看看？
然后你用的 xadmin 是我代码里的 xadmin 吗，我刚刚添加了课程，是没问题的呀

**Comment by ghost** [comment]
把哪一段代码截图？ 我的xamdin 不一定是跟你的一样

**Comment by kele59** [comment]
如果是 xadmin 的问题我恐怕解决不了，我测试了我本地 & 服务器上的代码，添加课程是百分百没问题的。你可以检查下是不是哪里写错了

**Comment by ghost** [comment]
好的，我再看看。我的代码检查过应该是没问题，有可能是xadmin的问题。我是不是可以直接clone你的去部署。

**Comment by kele59** [comment]
@a8926764 代码随意使用
