### ISSUE TITLE
docker-compose up -d 失败

### ISSUE THREAD

**Issue by ghost** [zaxlct/MxOnline_Django#36]
win7环境

![20170919110317](https://user-images.githubusercontent.com/15135197/30574105-6bc6a63a-9d2a-11e7-8cfd-d7ae85511ef8.png)

**Comment by kele59** [comment]
这个是 docker 方面的问题，这个...我不是很熟悉，sorry 爱莫能助

**Comment by ghost** [comment]
没关系  谢谢
