### ISSUE TITLE
django.db.utils.InternalError: (1067, "Invalid default value for 'tag'")

### ISSUE THREAD

**Issue by ghost** [zaxlct/MxOnline_Django#37]
全部clone的代码。不能migrate。环境配置：python3.5 virtualenv 其余的都是make dev

**Comment by kele59** [comment]
@a8926764 
mysql 什么的都装了吧？
建立一个名为 imooc 数据库了吗？

**Comment by ghost** [comment]
mysql安装了，也建立imooc数据库了，也在setting里面配置了

**Comment by ghost** [comment]
@zaxlct

**Comment by ghost** [comment]
我搞定了。
解决方法：
1、把你app的migrations下边所有的00开头的文件都删除。
2、删除数据库里面的imooc数据库。
3、重新创建imooc数据库，同时设置编码格式。
CREATE DATABASE 数据库名 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
参考：[http://www.bubuko.com/infodetail-1949094.html](url)

**Comment by kele59** [comment]
@a8926764 厉害。
