### ISSUE TITLE
Table 'imooc.auth_user' doesn't exist

### ISSUE THREAD

**Issue by cnbillow** [zaxlct/MxOnline_Django#4]
登陆后台http://127.0.0.1:8000/admin/auth/user/出错。Table 'imooc.auth_user' doesn't exist
这个表确实没有生成。为什么呢？

**Comment by kele59** [comment]
@cnbillow 
因为我们使用了 UserProfile 这个表代替了 django 自带的 auth_user 表。
所以 admin 需要再配置一下，具体可以看一下提交的代码。
