### ISSUE TITLE
执行make migrate时候报错！！！！

### ISSUE THREAD

**Issue by ChouCat** [zaxlct/MxOnline_Django#47]
执行make migrate时候报错，
django.core.exceptions.ImproperlyConfigured: mysqlclient 1.3.13 or newer is required; you have 0.7.10.None.

===========

[root@VM_0_13_centos ~]# pip freeze
Django==2.2.10
django-crispy-forms==1.6.1
django-debug-toolbar==2.2
django-formtools==2.0
django-pure-pagination==0.3.0
django-simple-captcha==0.4.6
httplib2==0.10.3
olefile==0.46
Pillow==4.0.0
PyMySQL==0.7.10
pytz==2019.3
six==1.14.0
sqlparse==0.3.0

=========

[root@VM_0_13_centos ~]# pip install PyMySQL==1.3.13
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement PyMySQL==1.3.13 (from versions: 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.6.2, 0.6.3, 0.6.4.dev1, 0.6.4, 0.6.6, 0.6.7, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.7.10, 0.7.11, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.9.2, 0.9.3)
ERROR: No matching distribution found for PyMySQL==1.3.13

**Comment by kele59** [comment]
百度下就能解决~
