### ISSUE TITLE
后台添加课程机构出错。

### ISSUE THREAD

**Issue by cnbillow** [zaxlct/MxOnline_Django#5]
封面图无法添加。
![image](https://cloud.githubusercontent.com/assets/5892849/25089738/7307a79e-23ba-11e7-8aee-9053bf5c008d.png)

**Comment by kele59** [comment]
我这边尝试添加了课程机构没有错误。
![image](https://cloud.githubusercontent.com/assets/14342431/25092082/b5aaedb4-23be-11e7-8065-f594f80b55d7.png)
添加完成后，封面图实际上存储的是一个「文件路径」，而且这个路径有一定的格式，具体可以看一下`apps/organization/models.py` 里：
```python
image = models.ImageField(upload_to='org/%Y/%m', verbose_name='封面图')
```
同时 setting.py 里关于 media 目录的配置是否加上了呢？
urls.py 里关于 media 的配置是否也加上了呢？

可以在 setting.py 和 urls.py 里搜索一下 `media` ，看看有哪些配置。

**Comment by cnbillow** [comment]
点击　课程－增加课程，点击课程机构后面的加号。无法添加课程机构。
![image](https://cloud.githubusercontent.com/assets/5892849/25132474/ae95bee8-2484-11e7-80d9-d07665c5709c.png)
