### ISSUE TITLE
点击课程－增加课程，点击课程机构后面的加号。无法添加课程机构。

### ISSUE THREAD

**Issue by cnbillow** [zaxlct/MxOnline_Django#6]
#5 的详细说明
![image](https://cloud.githubusercontent.com/assets/5892849/25132569/eecffb54-2484-11e7-9b4d-13d7ad388cbd.png)

**Comment by kele59** [comment]
发现问题：进行 ajax 操作时，上传图片的 image 字段，即使上传成功也不会提交
可能是 xadmin 的 BUG，暂时还没有解决思路。
