### ISSUE TITLE
xadmin不是跟py3不太适配么？

### ISSUE THREAD

**Issue by json988** [zaxlct/MxOnline_Django#9]
xadmin不是跟py3不太适配么？ py2和py3实在是太难选了，本人想做个自己python小项目，一直纠结于py2还是py3. 和用不用xadmin的问题。也是看了这个教程。能给点意见么？

**Comment by json988** [comment]
除了xadmin还有什么可替代的么

**Comment by kele59** [comment]
https://github.com/zaxlct/MxOnline_Django/tree/xadmin-python3
修改了 xadmin 的源码，基本上和 py3.5 兼容，可以使用
